stages:
  - play

GitTerra:
  stage: play
  script:
    - echo "Let's play GitTerra!"
    - set
    - find . -not -path './.git' -not -path './.git/*'
    - touch gitterra.html
  artifacts:
    paths:
      - gitterra.html
    expire_in: 1 week
