stages:
  - play

GitTerra:
  stage: play
  script:
    - echo "Let's play GitTerra!"
    # - set
    # - find . -not -path './.git' -not -path './.git/*'
    - mkdir -p /tmp/gitterra
    - wget https://github.com/boyter/scc/releases/download/v3.2.0/scc_Linux_x86_64.tar.gz -O /tmp/gitterra/scc.gz
    - tar -C /tmp/gitterra -xvf /tmp/gitterra/scc.gz
    - chmod +x /tmp/gitterra/scc
    - time /tmp/gitterra/scc . --format json --output gitterra.json
    - touch gitterra.html
  artifacts:
    paths:
      - gitterra.html
      - gitterra.json
