spec:
  inputs:
    stage:
      default: play
---
stages:
  - play

GitTerra:
  stage: $[[ inputs.stage ]]
  script:
    - echo "Let's play GitTerra!"
    - mkdir maps
    - touch maps/index.html
  artifacts:
    paths:
      - maps/
    expire_in: 1 week
