stages:
  - play

GitTerra:
  stage: play
  script:
    - echo "Let's play GitTerra!"
    # - set
    # - find . -not -path './.git' -not -path './.git/*'
    - mkdir -p /tmp/gitterra
    - git clone https://gitlab.com/gitterra/GitTerra.git /tmp/gitterra/gitterra
    - wget https://github.com/boyter/scc/releases/download/v3.2.0/scc_Linux_x86_64.tar.gz -O /tmp/gitterra/scc/scc.gz
    - tar -C /tmp/gitterra/scc -xvf /tmp/gitterra/scc/scc.gz
    - chmod +x /tmp/gitterra/scc/scc
    - time /tmp/gitterra/scc/scc . --format json --output gitterra.json
    - node /tmp/gitterra/gitterra/src/generateMap.js
  artifacts:
    paths:
      - gitterra.html
      - gitterra.json
