stages:
  - GitTerra

GitTerra:
  stage: $[[ inputs.stage ]]
  script:
    - echo "Let's play GitTerra!"
    - mkdir maps
    - touch maps/index.html
  artifacts:
    - path: maps/
      name: gitterra-log
      when: always
