stages:
  - play

GitTerra:
  stage: play
  script:
    - echo "Let's play GitTerra!"
    - find .
    - mkdir maps
    - touch maps/index.html
  artifacts:
    paths:
      - maps/
    expire_in: 1 week
